### ISSUE TITLE
Key Vault name is not idempotent

### ISSUE THREAD

**Issue by shawntmeyer** [Azure/avdaccelerator#257] opened 2022-12-01 19:35 UTC
When I run the same deployment multiple times with the same parameters, I get a new Key Vault for each deployment.

**Comment by moisesjgomez** [comment] 2023-01-03 18:36
@shawntmeyer This AVD deployment is designated as greenfield and as such for new deployments, so this behavior is as intended. We are working on brownfield scenarios, but the code is not ready yet.

**Comment by swathibhat1** [comment] 2023-01-04 18:01
Closing this feature/enhancement in view of the above discussion/comment.

**Closed by swathibhat1** 2023-01-04 18:01 UTC
